CREATE TABLE t1(x INTEGER PRIMARY KEY ASC, y, z);      CREATE TABLE t2(x INTEGER, y, z, PRIMARY KEY(x ASC));
CREATE TABLE t3(x INTEGER, y, z, PRIMARY KEY(x DESC));
  CREATE TABLE t4(x INTEGER, y, z, PRIMARY KEY(x ASC));